apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-cm-env
  namespace: default
data:
  env1: "env-value1"
  env2: "env-value2"

---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-env
spec:
  containers:
  - name: test-container
    image: busybox
    command: [ "/bin/sh", "-c", "env" ]
    env:
      - name: ENV1
        valueFrom:
          configMapKeyRef:
            name: demo-cm-env
            key: env1
      - name: ENV2
        valueFrom:
          configMapKeyRef:
            name: demo-cm-env
            key: env2
  restartPolicy: Never