apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-cm-file
  namespace: default
data:
  file1: "file1 text\n"
  file2: "file2 text\n"

---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-file
spec:
  containers:
    - name: test-container
      image: busybox
      command: [ "/bin/sh", "-c", "cat /etc/config/*" ]
      volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: demo-cm-file
  restartPolicy: Never