---
apiVersion: v1
kind: Pod
metadata:
  name: private-registry
spec:
  containers:
    - name: private-registry
      image: registry:latest
      ports:
        - containerPort: 5000
          hostPort: 5000
