kind: PersistentVolume
apiVersion: v1
metadata:
  name: demo-pv
  labels:
    kubernetes.io/cluster-service: "true"
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /var/vols/demo
    server: 16.187.191.97

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: demo-pvc
  namespace: default
  labels:
    kubernetes.io/cluster-service: "true"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
        kubernetes.io/cluster-service: "true"
        