---
apiVersion: v1
kind: Service
metadata:
  name: kube-registry
  namespace: kube-system
  labels:
    k8s-app: kube-registry
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "KubeRegistry"
spec:
  ports:
    - name: registry
      port: 5000
      protocol: TCP
  selector:
    k8s-app: kube-registry
---
apiVersion: v1
kind: Pod
metadata:
  name: private-registry
  namespace: kube-system
  labels:
    k8s-app: kube-registry
    version: v0
    kubernetes.io/cluster-service: "true"
spec:
  initContainers:
  - name: install
    image: busybox
    command:
      - touch
      - /var/lib/registry/init.txt
    volumeMounts:
    - name: registry-storage
      mountPath: "/var/lib/registry"
  containers:
  - name: private-registry
    image: registry:latest
    imagePullPolicy: Always
    lifecycle:
      postStart:
        exec:
          command: ["touch", "/var/lib/registry/postStart.txt"]
      preStop:
        exec:
          command: ["touch", "/var/lib/registry/preStop.txt"]
    resources:
      limits:
        cpu: 1000m
        memory: 400Mi
      requests:
        cpu: 100m
        memory: 200Mi
    livenessProbe:
      tcpSocket:
        port: 5000
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 10     
    readinessProbe:
      tcpSocket:
        port: 5000
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 10 
    env:
    - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
      value: /var/lib/registry
    - name: MY_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: MY_POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: MY_POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    ports:
    - containerPort: 5000
#      hostPort: 5000
    volumeMounts:
    - name: registry-storage
      mountPath: /var/lib/registry
  volumes:
  - name: registry-storage
    emptyDir: {}
  restartPolicy: Always