apiVersion: v1
kind: Pod
metadata: 
  name: test-volume
spec:
  containers:
  - name: test-volume
    image: busybox
    command: [ "/bin/sh", "-c", "sleep 3600" ]
    volumeMounts:
    - mountPath: /mnt
      name: test-volume
  volumes:
  - name: test-volume
    hostPath: 
      path: /root 
      type: Directory
      