apiVersion: v1
kind: Pod
metadata: 
  name: test-nodeselector
spec:
  nodeSelector: 
    nodetype: master
  containers:
  - name: test-nodeselector
    image: busybox
    command: [ "/bin/sh", "-c", "sleep 3600" ]
      