apiVersion: v1
kind: Pod
metadata: 
  name: test-volume1
spec:
  containers:
  - name: test-volume
    image: busybox
    command: [ "/bin/sh", "-c", "sleep 3600" ]
    volumeMounts:
    - mountPath: /mnt
      name: test-pv
      subPath: test-subpath
  volumes:
  - name: test-pv
    persistentVolumeClaim:
      claimName: demo-pvc
      